const questions = [
  "What have you created that you are most proud of?",
  "What's the best thing you got from one of your parents?",
  "What bends your mind every time you think about it?",
  "In your group of friends, what role do you play?",
  "What incredibly strong opinion do you have that is completely unimportant in the grand scheme of things?",
  "What's your favorite piece of clothing you own?",
  "What fictional place would you most like to go to?",
  "What's one place you've travelled that you never want to go back to?",
  "When people come to you for help, what do they usually want help with?",
  "What are you interested in that most people haven't heard of?",
  "Mountains or ocean?",
  "What was your best birthday?",
  "Pizza or tacos?",
  "What's the story behind one of your scars?",
  "Pancakes or waffles?",
  "Pirates or ninjas?",
  "What was the best compliment you've ever received?",
  "If you lost all of your possessions but one, what would you want it to be?",
  "Who inspires you to be better?",
  "What dumb accomplishment are you most proud of?",
  "When was the last time you changed your opinion about something major?",
  "What is something you can never seem to finish?",
  "What is one of your favorite smells?",
  "If you had to change your name, what would you change it to?",
  "What are you a natural at?",
  "What do you like most about your family?",
  "Have you ever saved someone's life?",
  "What's an unpopular opinion you have?",
  "Who is one of your best friends, and what do you love about them?",
  "Do you have any nicknames?",
  "What's one of your favorite comfort foods?",
  "What is your theme song?",
  "What is one of the great values that guides your life?",
  "What's your favorite book?",
  "What's the last book you gave up on and stopped reading?",
  "What's the worst movie you've ever seen?",
  "What issue will you always speak your mind about?",
  "What would you do on a free afternoon in the middle of the week?",
  "Pet peeves?",
  "What's the best piece of advice you ever received?",
  "Who was your favorite teacher and why?",
  "If you could have any superpower, what would it be and why?",
  "What's on your bucket list this year?",
  "If you could live in a book, TV show, or movie, what would it be?",
  "What languages do you speak?",
  "Would you rather be stuck on a broken ski lift or a broken elevator?",
  "If you were a vegetable, what vegetable would you be?",
  "What makes you cry?",
  "Who are some of your heroes?",
  "What's something you wish you'd figured out sooner?",
  "What's your favorite candy?",
  "What's your worst habit?",
  "Favorite city?",
  "What's your go-to dance move?",
  "Do you ever sing when you're alone? What songs?",
  "What's your earliest memory?",
  "What's something you learned in the last week?",
  "What story does your family always tell about you?",
  "What talent would you show off in a talent show?",
  "Where was your secret hiding place as a child?",
  "What's the best part of rain?", "What's your plan for surviving a zombie invasion?", 'If it was possible to transplant your brain to stay alive for another 100 years, would you?', "Is there a personality trait that you'd like to adopt from one of your friends?", 'Of all the problems in the world, which one would you like to see solved first?', 'What is something that you absolutely will not put up with?', "What do you believe is the biggest thing that's currently holding you back from success?", 'In emergency situations, how do you react?', 'Do you have something special that picks you up when you feel down? What is it?', 'What do you love most about where you grew up?', 'Do you have any phobias?', 'What is something you own that you have never used?', 'Can you describe your personal style?', 'What destination is at the top of your list to visit?', "What's the embarrassing story that your parents used to tell others about you?", "What's your favorite daily routine?", 'What are the top three qualities you admire in others?', 'What was the last big mistake you made?', 'What uncommon thing would you like to see become more common?', 'What is the last big goal you accomplished?', 'Have you ever done something embarrassing around a former crush?', "What's the most difficult thing that you still do each day?", "What's simply too difficult?", 'What is your opinion on social media?', 'What obscure interest do you have?', "What's the last thing you did alone and you enjoyed?", 'Do you have a secret place?', 'What is something that you find mildly annoying, but not annoying enough to do anything about?', "What's the strangest situation you ever found yourself in?", 'What do you remember most about your first crush?', 'If you had to change the language you speak, which one would you choose?', "What's the most recent interesting conversation you had?", 'If you knew you could live forever, how would you spend your days differently?', 'What has been your biggest financial mistake?', 'Where do you draw the line?', 'If someone were to sum you up with a phrase, what would that phrase be?', 'If you could have the attention of the world for one minute, what would you say?', 'If you were to devote your life to art, what type of art would that be?', 'What recent experience made you feel old?', 'Do you people watch? If so, where do you like to do this most?', 'What was the best thing you learned in the past year?', 'What is the last big argument you go into and who was it with?', "What's your story about being under intense pressure and how did you handle it?", 'How long did it take for you to come up with your current signature?', 'What was the last meltdown that you witnessed?',
  "What is your current go-to song to dance to when nobody is around?",
  "What's the most difficult thing about being you?",
  "What's the story behind your last rant?",
  "How well do you trust your gut feelings?",
  "If you had an extra hour a day that had to be allocated to one specific purpose, how would you use it?",
  "What's your favorite room in your house and why?",
  "What would be the best thing about losing your hearing?",
  "If you could have any person become a member of your family, who would you choose?",
  "What's the best trick someone has ever played on you?",
  "What do you consider the best decision you've made thus far in your life?",
  "What are the top three qualities you admire in others?",
  "What was the last big mistake you made?",
  "Without saying the category, what are your top five?",
  "Do you have an app on your phone that you use even though you hate it?",
  "What's the last thing that you gave up on? Are you happy or disappointed?",
  "What do you think would be the worst thing about being famous?",
  "Which of your past teachers would you like to sit down with and talk to today?",
  "How long did it take for you to come up with your current signature?",
  "What question have people recently been constantly asking you?",
  "What bad decision did you make that actually turned out to be a good decision?",
  "What do you think people pretend to like when they really don't?",
  "What's the most difficult thing that you still do each day?",
  "Who is the luckiest person you know?",
  "What do you think is the most valuable resource?",
  "What do you wish you had learned five years before you did?",
  "Are you currently where you want to be in life?",
  "What is something you thought would be a great idea but was terrible when you actually did it?",
  "What's your opinion on social media?",
  "What little thing instantly tells you that a person is good?",
  "Do you have a favorite brand?",
  "Is there anything that makes you far angrier than it should?",
  "At what age did you think you become an adult and when do you actually think you did?",
  "What is the most selfish thing you do that you're okay with?",
  "Do you have any unusual fears?",
  "What's the one thing that you seem to constantly lose?",
  "What is your best shower thought?",
  "Do you name inanimate objects?",
  "Do you have any apps on your phone that you've never used?",
  "What song currently speaks to you the most?",
  "What do you see happening in your future?",
  "Did you ever have a huge rival? Was the rivalry friendly or fierce?",
  "What is the messiest situation you've ever encountered?",
  "What weird thing do you do when nobody else is around?",
  "If you could choose to be famous for something, what would it be?",
  "What do you find attractive that others might find unusual?",
  "What is something you predict will exist in 10 years that doesn't today?",
  "How far back can you trace your family tree?",
  "What is your biggest regret from the last month?",
  "What's something that you would be willing to stay up all night to do?",
  "What's the story behind your favorite memento?",
  "Would the world be better or worse if superheroes existed?",

  "If you had to pick a single word to describe this year so far, what would it be?",
  "What do you think is your most creative ability?",
  "Do you name inanimate objects?",
  "What's the most difficult choice you were asked to make?",
  "What are you currently juggling in your life?",
  "What's your opinion on tipping?",
  "What thing from childhood do you still enjoy to this day?",
  "What did you recently learn the hard way?",
  "How do you approach life?",
  "What's something interesting about you that few people know?",
  "If each person had a warning label, what would yours say?",
  "Where's the next place you want to visit?",
  "What's the most interesting conversation you eavesdropped on?",
  "Can you describe your personal style?",
  "What's something that you recently learned that everyone else already knew?",
  "What have you done that you didn't like, but would you be willing to give it another shot?",
  "What mode of transportation have you never tried?",
  "What is the oddest form of entertainment you enjoy?",
  "What is the next big purchase you're currently saving for?",
  "Without saying the category, what are your top five?",
  "What is your opinion on social media?",
  "If you could assign one household chore to someone else, what would it be?",
  "In emergency situations, how do you react?",
  "How often do you find yourself daydreaming?",
  "What's your \"famous person\" story?",
  "What do you spend too much time doing?",
  "What does it mean to \"live a good life\" in your opinion?",
  "What little thing do you do that you don't think many people notice?",
  "Is time currently passing quickly or slowly for you?",
  "Do you have any apps on your phone that you've never used?",
  "What technology advance are you looking forward to in the future?",
  "Is it better to read books in electronic form or actually hold the book?",
  "What do you do in secret that you're proud of?",
  "What part of your body currently doesn't feel 100%?",
  "What would someone who doesn't know you well be most surprised about?",
  "What's the best way you've found to calm yourself when you get stressed?",
  "Can you name 5 things you wouldn't do for a million dollars?",
  "Where do you see yourself in 5 years?",
  "What's the last thing that you gave up on? Are you happy or disappointed?",
  "What was an experience you didn't think much about at the time, but it ultimately made you a stronger person?",
  "What food do you have a love-hate relationship with?",
  "What uncommon thing would you encourage everyone to try once?",
  "What is socially acceptable today that you think won't be in 10 years?",
  "Is there anything that makes you far angrier than it should?",
  "What are some things don't you understand about the opposite sex?",

  "What do you hope to be an expert about at some point in your life?",
  "If you were to devote your life to art, what type of art would that be?",
  "If you could have the attention of the world for one minute, what would you say?",
  "What is the assumption that people make about you that's totally wrong?",
  "What's the most interesting thing you have in your pockets right now?",
  "Who is someone you need to contact that you haven't?",
  "What's your favorite form of entertainment?",
  "What's your opinion on naps?",
  "Have you ever had to complain to management? Why?",
  "What is the last thing that you totally overreacted to?",
  "What one thing would significantly make your life better?",
  "Why haven't you done it yet?",
  "How do you approach life?",
  "What have you recently felt grateful for?",
  "Who is someone you recently thought about that you haven't seen or talked to in years?",
  "What is the strangest way you met one of your friends?",
  "What destination is at the top of your list to visit?",
  "Of all the problems in the world, which one would you like to see solved first?",
  "Is there a part of your culture that you don't like?",
  "What is the next thing you have on your to-buy list?",
  "If you had to walk away from one technology in your life, what would it be?",
  "What do you think is the most useful skill to know?",
  "What was the last meltdown that you witnessed?",
  "What have you done that you didn't like, but would you be willing to give it another shot?",
  "What do you consider the best decision you've made thus far in your life?",
  "Can you explain love?",
  "What's the story about the last time you cried?",
  "What is something that you don't mind waiting for?",
  "Have you ever let someone else get punished for something you did?",
  "What are you currently juggling in your life?",
  "What is something that you would really like to try again?",
  "What future year are you most looking forward to arriving?",
  "Why?",
  "What is something that will instantly annoy you?",
  "Are you a planner or more of a go with whatever happens when it comes to travel?",
  "If you had to choose, would you rather be too hot or too cold?",
  "What part of history do you find most interesting?",
  "What have you been thinking about lately that has kept you up at night?",
  "What's something you find attractive that others may not?",
  "What's the last thing that you broke and how did it happen?",
  "What was an experience you didn't think much about at the time, but it ultimately made you a stronger person?",
  "What is the oddest form of entertainment you enjoy?",
  "What recent situation was nearly a disaster, but you were able to prevent it?",
  "What was the last big mistake you made?",
  "What assumption have you made that ended up being completely incorrect?",
  "How much damage could your best friend do to you if you ever had a falling out?",
  "What app or website completely changed your life?"

]

export default questions